* Global WITCH model

set global 'Regions' /
world
/;

$batinclude 'regions/iso3.inc'

set map_global_iso3(global,iso3) 'Mapping between R5 regions and countries'/

world.CAN # Canada
world.JPN # Japan
world.NZL # New Zealand

world.CHN  # R5ASIA
world.HKG  # Small countries: Honk Kong
world.MAC  #                  Macao
world.TWN  #                  Taiwan

world.ASM  # East Asia
world.BRN
world.CCK
world.FJI
world.FSM
world.GUM
world.IDN
world.KHM
world.KIR
world.PRK
world.LAO
world.MHL
world.MMR
world.MNG
world.MNP
world.MYS
world.NCL
world.PHL
world.PLW
world.PNG
world.PYF
world.SGP
world.SLB
world.THA
world.TLS
world.TON
world.VNM
world.VUT
world.WSM
world.KSV
world.VIR

world.AUS # Australia
world.KOR # South Korea
world.ZAF # South Africa

world.ABW
world.AIA
world.ARG
world.ATG
world.BES
world.BHS
world.BLM
world.BLZ
world.BOL
world.BRA
world.BRB
world.CHL
world.COL
world.CRI
world.CUB
world.CUW
world.CYM
world.DMA
world.DOM
world.ECU
world.FLK
world.GLP
world.GRD
world.GTM
world.GUF
world.GUY
world.HND
world.HTI
world.JAM
world.KNA
world.LCA
world.MAF
world.MEX
world.MSR
world.MTQ
world.NIC
world.PAN
world.PER
world.PRI
world.PRY
world.SLV
world.SUR
world.SXM
world.TTO
world.URY
world.VCT
world.VEN

world.IND # R5ASIA

world.ARE
world.BHR
world.DJI
world.DZA
world.EGY
world.ESH
world.IRN
world.IRQ
world.ISR
world.JOR
world.KWT
world.LBN
world.LBY
world.MAR
world.OMN
world.PSE
world.QAT
world.SAU
world.SYR
world.TUN
world.YEM

world.BGR # EU countries (except EU-15+Malta)
world.CYP #
world.CZE #
world.EST #
world.HUN #
world.LTU #
world.LVA #
world.POL #
world.ROU #
world.SVK #
world.SVN #
world.MLT # Malta was formely in R5MAF
world.HRV # Croatia was formely in R5REF

world.AUT # EU-15 Countries
world.BEL #
world.DEU #
world.DNK #
world.ESP #
world.FIN #
world.FRA #
world.GBR #
world.GRC #
world.IRL #
world.ITA #
world.LUX #
world.NLD #
world.PRT #
world.SWE #
world.LIE # LiechR5REFnsR5REFin
world.NOR # Norway
world.CHE # Switzerland
world.GRL # Greenland (to Denmark)
world.ISL # Iceland
world.FRO # Island Feroe
world.ALA # Small islands/countries
world.AND #
world.GGY #
world.GIB #
world.IMN #
world.JEY #
world.MCO #
world.SJM #
world.SMR #
world.VAT #
world.SPM # St Pierre et Miquelon (to France)

world.AFG
world.BGD
world.BTN
world.LKA
world.MDV
world.NPL
world.PAK

world.AGO
world.BEN
world.BWA
world.BFA
world.BDI
world.CMR
world.CPV
world.CAF
world.TCD
world.COM
world.COG
world.COD
world.CIV
world.GNQ
world.ERI
world.ETH
world.GAB
world.GMB
world.GHA
world.GIN
world.GNB
world.KEN
world.LSO
world.LBR
world.MDG
world.MWI
world.MLI
world.MRT
world.MUS
world.MYT
world.MOZ
world.NAM
world.NER
world.NGA
world.REU
world.RWA
world.STP
world.SEN
world.SYC
world.SHN
world.SLE
world.SOM
world.SSD
world.SDN
world.SWZ
world.TZA
world.TGO
world.UGA
world.ZMB
world.ZWE

world.ALB
world.ARM
world.AZE
world.BLR
world.BIH
world.GEO
world.KAZ
world.KGZ
world.MKD
world.MDA
world.MNE
world.RUS
world.SRB
world.TJK
world.TUR
world.TKM
world.UKR
world.UZB

world.USA       

* other small R5REFrritories
world.CXR # Christmas Island (to Australia)
world.ATA # Antarctica
world.ATF # French Southern R5REFrritories
world.BMU # Bermuda
world.BVT # Bouvet Island
world.COK # Cook Islands
world.HMD # Heard Island and McDonald Islands
world.IOT # British R5ASIAn Ocean R5REFrritory
world.NFK # Norfolk Island
world.NIU # Niue
world.NRU # Nauru
world.PCN # Pitcairn
world.SGS # South Georgia and the South Sandwich Islands
world.TCA # Turks and Caicos Islands
world.TKL # Tokelau
world.TUV # Tuvalu
world.UMI # UniR5REFd StaR5REFs Minor Outlying Islands
world.VGB # Virgin Islands, British
world.WLF # Wallis and Futuna

/;


